# Generated by Django 5.2.6 on 2025-09-10 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=20, unique=True)),
                ("train_name", models.CharField(max_length=100)),
                ("current_mileage", models.IntegerField(default=0)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK - Ready for Service"),
                            ("minor_maintenance", "Minor Maintenance Required"),
                            ("cannot_schedule", "Cannot Schedule - Critical Issues"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField(default=99)),
                (
                    "status_notes",
                    models.TextField(
                        blank=True, help_text="Brief explanation of current status"
                    ),
                ),
                ("current_stabling_bay", models.CharField(blank=True, max_length=50)),
                ("cleaning_status", models.CharField(default="Clean", max_length=100)),
                ("maintenance_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rank", "train_number"],
            },
        ),
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_cards",
                        to="inductapp.train",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="certificates/")),
                ("issue_date", models.DateField(null=True)),
                ("expiry_date", models.DateField(null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="inductapp.train",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("train_operator", "Train Operator"),
                            ("metro_officer", "Metro Officer"),
                            ("cleaner", "Cleaner"),
                            ("maintenance_worker", "Maintenance Worker"),
                            ("staff1", "Staff Level 1"),
                            ("staff2", "Staff Level 2"),
                        ],
                        default="staff1",
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
